### ISSUE TITLE
Fails to build with ghc-9.0

### ISSUE THREAD

**Issue by lehins** [fpco/th-utilities#19]
Here is the build error when `th-utilities` is compiled with ghc-9.0
It seems that ghc-8.x and ghc >= 9.2 are not affected.

```
Preprocessing library for th-utilities-0.2.5.1...
Building library for th-utilities-0.2.5.1...
Error: [Cabal-7125]
Failed to build th-utilities-0.2.5.1 (which is required by bench:bench from mempack-0.1.1.0). See the build log above for details.
[1 of 7] Compiling TH.Derive.Internal ( src\TH\Derive\Internal.hs, dist\build\TH\Derive\Internal.o )
[2 of 7] Compiling TH.FixQ          ( src\TH\FixQ.hs, dist\build\TH\FixQ.o )
[3 of 7] Compiling TH.RelativePaths ( src\TH\RelativePaths.hs, dist\build\TH\RelativePaths.o )
[4 of 7] Compiling TH.Utilities     ( src\TH\Utilities.hs, dist\build\TH\Utilities.o )

src\TH\Utilities.hs:192:43: error:
Error:     Data constructor not in scope: CharTyLit :: Char -> TyLit
    |
192 |                 ['\'', c, '\''] -> LitT $ CharTyLit c
    |                                           ^^^^^^^^^

Error: Process completed with exit code 1.
```

**Comment by mgsloan** [comment]
Ah, good catch, OBOE in template haskell min bound.  Fixed in https://github.com/fpco/th-utilities/commit/213354f59e61561160b1918b67a5f8acff3dbd62 and released in 0.2.5.2
